# Generated by Django 5.1.7 on 2025-10-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_complaint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='created_at',
            new_name='date_time',
        ),
    ]
