# Generated by Django 5.1.7 on 2025-10-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_created_at_complaint_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='address',
            field=models.TextField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
