# Generated by Django 5.1.7 on 2025-10-06 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_complaint_address_complaint_location_complaint_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='conpass',
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('request_type', models.CharField(choices=[('Public Safety', 'Public Safety'), ('Sanitation / Hygiene', 'Sanitation / Hygiene'), ('Road / Traffic Issues', 'Road / Traffic Issues'), ('Electricity / Water Supply', 'Electricity / Water Supply'), ('Government Services', 'Government Services'), ('Others', 'Others')], max_length=50)),
                ('other_type', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.signup')),
            ],
        ),
    ]
