# Generated by Django 5.1.7 on 2025-10-06 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_signup_conpass_alter_signup_password_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestItem',
            new_name='request_form',
        ),
    ]
