# Generated by Django 5.1.7 on 2025-10-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_requestitem_request_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_form',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='request_form',
            name='user',
        ),
    ]
