# Generated by Django 5.1.7 on 2025-10-06 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_request_form_created_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='request_form',
            new_name='Request',
        ),
    ]
