# Generated by Django 5.1.7 on 2025-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_login_admin_login_eo_login_supervisor_signup_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='conpass',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signup_admin',
            name='conpass',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signup_eo',
            name='conpass',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='signup_supervisor',
            name='conpass',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
