# Generated by Django 5.1.7 on 2025-10-08 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_task_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login_supervisor',
            new_name='Admins',
        ),
        migrations.DeleteModel(
            name='Login_Admin',
        ),
        migrations.DeleteModel(
            name='Login_EO',
        ),
        migrations.DeleteModel(
            name='Signup_Admin',
        ),
        migrations.DeleteModel(
            name='Signup_EO',
        ),
        migrations.DeleteModel(
            name='Signup_supervisor',
        ),
        migrations.RenameField(
            model_name='admins',
            old_name='phoneno',
            new_name='username',
        ),
    ]
