# Generated by Django 5.1.7 on 2025-10-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_rename_login_supervisor_admins_delete_login_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=10)),
                ('supervisor_id', models.CharField(max_length=50, unique=True)),
                ('area', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('conpass', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
