# Generated by Django 5.2.7 on 2025-10-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='supervisor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
