# Generated by Django 5.2.7 on 2025-10-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
