# Generated by Django 5.2.7 on 2025-10-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_signup_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
