# Generated by Django 5.2.7 on 2025-10-11 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_signup_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='supervisor_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
