# Generated by Django 5.2.7 on 2025-10-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_request_area_request_supervisor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_posts', to='myapp.login'),
        ),
    ]
