# Generated by Django 5.2.7 on 2025-10-13 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_login_role_login_username_post_deleted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='deleted_by',
        ),
        migrations.AddField(
            model_name='post',
            name='deleted_by',
            field=models.TextField(blank=True, default=''),
        ),
    ]
