# Generated by Django 5.2.7 on 2025-10-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_remove_post_deleted_by_post_deleted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintSupervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('complaint_type', models.CharField(max_length=200)),
                ('supervisor_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], default='unverified', max_length=10)),
            ],
        ),
    ]
