# Generated by Django 5.2.7 on 2025-10-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_complaintsupervisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsupervisor',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsupervisor',
            name='complaint_type',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsupervisor',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsupervisor',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsupervisor',
            name='status',
            field=models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], default='unverified', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaintsupervisor',
            name='supervisor_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='complaintsupervisor',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
