# Generated by Django 5.2.7 on 2025-10-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_alter_complaintsupervisor_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='unverified', max_length=20),
        ),
    ]
