# Generated by Django 5.2.7 on 2025-10-14 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_eosignup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eosignup',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='eosignup',
            name='username',
        ),
    ]
