# Generated by Django 5.2.7 on 2025-12-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_eosignup_created_at_remove_eosignup_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='requests/'),
        ),
    ]
