# Generated by Django 5.2.7 on 2025-12-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_request_date_time_request_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
