# Generated by Django 5.2.7 on 2025-12-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_request_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eosignup',
            old_name='emp_number',
            new_name='eo_number',
        ),
        migrations.AddField(
            model_name='eosignup',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='eosignup',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eosignup',
            name='eo_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='eosignup',
            name='phone',
            field=models.CharField(max_length=15, null=True, unique=True),
        ),
    ]
