# Generated by Django 5.2.7 on 2025-12-12 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_rename_emp_number_eosignup_eo_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forgotpassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=10, null=True)),
                ('phoneno', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('newpassword', models.CharField(max_length=100, null=True)),
                ('confirmpassword', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
