# Generated by Django 5.2.7 on 2025-12-12 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_forgotpassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
