# Generated by Django 5.2.7 on 2025-12-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_forgotpassword_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forgotpassword',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
