from django.urls import path, include
from rest_framework.routers import DefaultRouter
from . import views


urlpatterns = [
    path("",views.Startpage,name="Startpage"),
    path("welcome/", views.welcome, name="welcome"),
    path("welcome2/", views.welcome2, name="welcome2"),
    path("welcome3/", views.welcome3, name="welcome3"),
    path("welcome4/", views.welcome4, name="welcome4"),
    path("login/", views.loginpage, name="loginpage"),
    path("login2/", views.loginpage2, name="loginpage2"),
    path("login3/", views.loginpage3, name="loginpage3"),
    #path("requestform/", views.request_form, name="request_form"),
    path("complaint/", views.complaint_form, name="complaint_form"),
    path("delete_complaint/<int:pk>/", views.delete_complaint, name="delete_complaint"),
    path("Forgotpassword/", views.Forgotpassword, name="Forgotpassword"),
    # path("verify-otp/", views.verify_otp, name="verify_otp"),
    path('requestform/', views.requestform, name='requestform'),
    path("logout/", views.logout, name="logout"),
    path("logoutadmin/", views.logout2, name="logout2"),
    path("logoutsupervisor/", views.logout3, name="logout3"),
    path("logouteo/", views.logout4, name="logout4"),
    path("addeo/", views.Add_eo, name="Add_eo"),
    path("signup/", views.signup, name="signup"),
    # path("signup_suppage/", views.signup_supervisor, name="signup_suppage"),
    # path("signup_EOpage/", views.signup_EOpage, name="signup_EOpage"),
    #path("signup_Adminpage/", views.signup_Adminpage, name="signup_Adminpage"),   
    path('posts/', views.Posts, name='Posts'),
    path("addsupervisor", views.Add_supervisor, name="Add_supervisor"), 
    path("task/", views.Tasks, name="Tasks"),
    path("mainpage/", views.Mainpage, name="Mainpage"),
    path('mainadmin/', views.Mainpageadmin, name='Mainpageadmin'),
    path("mainsupervisor/", views.Mainsupervisor, name="Mainsupervisor"),
    path("addarea/", views.Add_area, name="Add_area"),
    path("Deletearea/", views.Delete_area, name="Delete_area"),
    path('upload_profile/', views.upload_profile, name='upload_profile'),
    path("complaintsupervisor/", views.complaintsupervisor, name="complaintsupervisor"),
    path("requestsupervisor/", views.requestsupervisor, name="requestsupervisor"),
    path('notifications/', views.notification_page, name='notification_page'),
    path('notifications/delete/<int:post_id>/', views.delete_post, name='delete_post'),
    path('notificationspublic/', views.notification_page2, name='notification_page2'),
    path('notificationeo/', views.notification_page3, name='notification_page3'),
    path('delete-post3/<int:post_id>/', views.delete_post3, name='delete_post3'),
    path('delte-post4/<int:post_id>/', views.delete_post4, name='delete_post4'),
    path('notificationspublic/delete2/<int:post_id>/', views.delete_post2, name='delete_post2'),
    path('toggle-status/<int:complaint_id>/', views.toggle_status, name='toggle_status'),
    path("trackstatus/", views.Trackstatus, name="Trackstatus"), 
    path("trackstatus2/", views.Trackstatus2, name="Trackstatus2"),
    path('toggle-request-status/<int:request_id>/', views.toggle_request_status, name='toggle_request_status'),
    path('eo/complaints/', views.eo_complaints, name='eo_complaints'),
    path('eo/requests/', views.eo_requests, name='eo_requests'),
    path('eo_dashboard/', views.eo_dashboard, name='eo_dashboard'),
    path('login4/', views.login4, name='login4'),
    path("eosignup/", views.eo_signup, name="eo_signup"),
    path("publicsignups/", views.public_signups, name="public_signups"),
    path('achievement/', views.achievement, name='achievment'),
    path('achievementsupervisor/', views.Achievementsupervisor, name='Achievementsupervisor'),
    path('complaintseo/', views.complaints_eo, name='complaints_eo'),
    path('requestseo/', views.requests_eo, name='requests_eo'),
    #path('forgotpassword/', views.forgotpassword, name='forgotpassword'),
]
